### ISSUE TITLE
Alpha & Beta version of workbox has released

### ISSUE THREAD

**Issue by SukkaW** [nuxt-community/workbox-cdn#1]
Google has released 4.0.0-alpha.0` and `4.0.0-beta.0` of workbox lib.
Should we make update?

Also, I think it is better to let CI check the version and automatically publish new version when one existed.

**Comment by pi0** [comment]
Sorry @SukkaW for the delay. I've created `next` branch with the release script. `4.0.0-rc.0` now available via NPM `@next`  tag.
