### ISSUE TITLE
How can i use the package

### ISSUE THREAD

**Issue by impons** [nuxt-community/workbox-cdn#12]
Hello! Could you provide some example to how use the option 2? I read the workbox documentation for Nuxt PWA and seems i have to use `workboxURL` property to make my project use this package instead cdn.

**Comment by pi0** [comment]
Hi! Nuxt PWA (3.x) module uses alternative CDN (of this package) by default. Do you need self hosted files? (This is wip for pwa module)

**Comment by impons** [comment]
Well as i read that the CDN hosted on storage.googleapis.com is sometimes unavailable i wanted to serve the workbox script from my own project.

**Comment by pi0** [comment]
Nuxt PWA (v3) CDN is not google storage but jsDelivr. Their uptime and availablity is near to 100% and content will be served via nearest geolocation. Probably even faster than your hosting 😉

The point is somewhere apps are being accessed behind firewall where no CDN is reachable at all. For this case, we need to implement support in pwa module itself. This package is already being published to NPM and locally installed.

**Comment by impons** [comment]
ok! thanks for your time :)
