### ISSUE TITLE
How could i load package locally ?

### ISSUE THREAD

**Issue by codergirll** [nuxt-community/workbox-cdn#15]
Hello,  i am using nuxt2.10 and @nuxtjs/pwa": "3.0.0-beta.19",
also i add this package to stop importing script from cdn jsdeliver.
this is my workbox config:
```
  workbox: {
    config: {
      modulePathPrefix: '/node_modules/workbox-cdn/workbox/workbox-sw.js',
    },
  },
```
the problem is when i build the project
the generated sw.js will look like this:

```
importScripts('https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-sw.js')

// --------------------------------------------------
// Configure
// --------------------------------------------------

// Set workbox config
workbox.setConfig({
  "modulePathPrefix": "/node_modules/workbox-cdn/workbox/workbox-sw.js",
  "debug": false
})
```
still i have the importscript from cdn,
how can i change or remove it?
and also i have these error on my console and network tab.
![2](https://user-images.githubusercontent.com/51401747/68051847-a2d05b00-fcfd-11e9-9e92-d9873f883aeb.png)
![1](https://user-images.githubusercontent.com/51401747/68051848-a368f180-fcfd-11e9-9fbf-a6a35745008c.png)

Thank you in Advance.

**Comment by codergirll** [comment]
Oh that was my mistake,
i wrote a script to copy workbox file in static folder 
then i add that in my nuxt config :
```
  workbox: {
      workboxURL: `/workbox/workbox-sw.js?${Date.now()}`,
  }
```
and it works. :)

**Comment by hadimajidi** [comment]
> Oh that was my mistake, i wrote a script to copy workbox file in static folder then i add that in my nuxt config :
> 
> ```
>   workbox: {
>       workboxURL: `/workbox/workbox-sw.js?${Date.now()}`,
>   }
> ```
> 
> and it works. :)

I have the same problem. could you please let me know what your solution is ?
Thx
