### ISSUE TITLE
Alpha version of workbox 5.0.0 has released

### ISSUE THREAD

**Issue by SukkaW** [nuxt-community/workbox-cdn#7]
Since workbox 5.0.0 alpha 1 and workbox alpha 2 is released, we should bump `package.json` to `v5.0.0-alpha.0`, then `v5.0.0-alpha.1` , then `v5.0.0-alpha.2`  to get update with it.

I am thinking about list published version from npm everyday & drop a new version for `workbox-cdn` if `workbox` has released a new version.

**Comment by pi0** [comment]
Master is now pointing to 5.x :)
